export default [
    {
      id: 1,
      position: "Web Developer",
      location: "Noida, sector-62",
      role: "Looking a full-stack developer with at least 1-year of experience in HTML, CSS, Javascript and beckend techologies.",
      company: "Cliffex Software Solutions",
      image: "https://i.pinimg.com/236x/cf/10/9e/cf109e7099ccf42fcdac7c9fce813ad6.jpg",
      salary: "2,30,000-3,00,000",
      mode: "work from home",
      arrangement: "full-time",
    },
    {
      id: 2,
      position: "Front-end Developer",
      location: "Noida, sector-101",
      role: "Looking a front-end developer with at least 1year of experience in HTML, CSS, Javascript.",
      company: "Novac Linus Co.",
      image: "https://i.pinimg.com/236x/de/c8/49/dec84941bea2476ab67eb6c1aa06083a.jpg",
      salary: "1,30,000-2,30,000",
      mode: "in-office",
      arrangement: "full-time",
    },
    {
      id: 3,
      position: "Content Writer",
      location: "Gurgaon",
      role: "Looking a content writer with 2-year experience with Nodejs, Express, MongoDB.",
      company: "Bada Business Corpration",
      image: "https://i.pinimg.com/236x/c9/a1/97/c9a197aad97604f7fd735776f36c8638.jpg",
      salary: "2,00,000-3,00,000",
      mode: "work from home",
      arrangement: "full-time",
    },
    {
      id: 4,
      position: "Manual Testing",
      location: "Delhi, Laxmi nagar",
      role: "Looking for a manual tester with at least testing of at least 10 apps.",
      company: "Safari Business",
      image: "https://i.pinimg.com/236x/f8/1f/fb/f81ffb30d242c0bab615e0a1785b5023.jpg",
      salary: "1,00,000-2,00,000",
      mode: "in-office",
      arrangement: "full-time",
    },
    {
      id: 5,
      position: "Web Designer",
      location: "Noida, sector-62",
      role: "Looking a web designer with at least 1-year of experience in HTML, CSS, Javascript and beckend techologies.",
      company: "Cliffex Software Solutions",
      time: "Now",
      image: "https://i.pinimg.com/236x/bb/29/4b/bb294bee041683dd7751388a6f5286a0.jpg",
      salary: "4,30,000-5,00,000",
      mode: "work from home",
      arrangement: "full-time",
    },
    {
      id: 6,
      position: "UI Developer",
      location: "Noida, sector-101",
      role: "Looking a UI developer with at least 1year of experience in HTML, CSS, Javascript.",
      company: "Novac Linus Co.",
      image: "https://i.pinimg.com/236x/92/a5/1f/92a51fa9bd09e32fc623c6c2717d945b.jpg",
      salary: "1,30,000-2,00,000",
      mode: "in-office",
      arrangement: "full-time",
    },
    {
      id: 7,
      position: "Backend Developer",
      location: "Gurgaon",
      role: "Looking a backend developer with 2-year experience with Nodejs, Express, MongoDB.",
      company: "Bada Business Corpration",
      image: "https://i.pinimg.com/236x/af/76/d7/af76d7faf9fe444f067f5f7f30c30ddc.jpg",
      salary: "4,00,000-5,00,000",
      mode: "in-office",
      arrangement: "full-time",
    },
    {
      id: 8,
      position: "Manual Testing",
      location: "Delhi, Laxmi nagar",
      role: "Looking for a manual tester with at least testing of at least 10 apps.",
      company: "Safari Business",
      image: "https://i.pinimg.com/236x/79/7b/e3/797be3f182aeaf9e8c10a4e405e78a0a.jpg",
      salary: "2,30,000-3,00,000",
      mode: "work from home",
      arrangement: "full-time",
    },
  ];